# LGKA+ App Configuration
# This file contains all app configuration that gets applied to both Android and iOS
# Change values here and run the setup script to apply to both platforms

# App Identity
app_name: "LGKA+"
app_description: "LGKA+ App - Digitaler Vertretungsplan"
package_name: "com.lgka"

# Version Configuration
version_name: "1.6.0"
version_code: "19"

# App Icon Configuration
app_icon_path: "assets/images/app-icons/app-logo.png"

# Android Specific
android:
  min_sdk: 21
  target_sdk: 34
  compile_sdk: 34

# iOS Specific
ios:
  deployment_target: "12.0"
  bundle_identifier: "com.lgka"

# Development Team (for iOS signing)
development_team: "M8M22924DJ" 