theme: jekyll-theme-minimal
title: LGKA
description: Digital Substitution Plan App by Luka Löhr
markdown: kramdown
baseurl: ""
url: ""
permalink: pretty
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default" 