name: Deploy HTML to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'impressum.html'
      - 'privacy.html'
      - 'docs/**'
      - '.github/workflows/deploy-ghpages.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        
      - name: Copy HTML files to docs directory
        run: |
          mkdir -p docs
          # Files are already in docs directory, no need to copy
          
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: './docs'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
